# Generated by Django 5.0.14 on 2026-07-26 04:38

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key', models.CharField(default=core.models.generate_api_key, editable=False, max_length=64, unique=True)),
                ('hostname', models.CharField(max_length=120)),
                ('mac_address', models.CharField(blank=True, db_index=True, max_length=32)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('os_info', models.CharField(blank=True, max_length=120)),
                ('device_type', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text="Uncheck to revoke a device's API key access.")),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='core.branch')),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('force_scan', 'Request immediate hardware scan'), ('force_sync', 'Force synchronization'), ('update_employee', 'Update employee information'), ('correct_asset', 'Correct asset details'), ('change_settings', 'Change application settings'), ('announcement', 'Send announcement/instruction'), ('maintenance_reminder', 'Schedule maintenance reminder')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_detail', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='core.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=60)),
                ('change_type', models.CharField(choices=[('Added', 'Added'), ('Removed', 'Removed'), ('Replaced', 'Replaced'), ('Updated', 'Updated')], max_length=10)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('employee_name', models.CharField(blank=True, max_length=120)),
                ('branch_name', models.CharField(blank=True, max_length=120)),
                ('computer_name', models.CharField(blank=True, max_length=120)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='core.device')),
            ],
            options={
                'verbose_name': 'Asset Change (Audit Log)',
                'verbose_name_plural': 'Asset Changes (Audit Log)',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_name', models.CharField(blank=True, max_length=200, verbose_name='System Model (Cabinet)')),
                ('cpu_serial', models.CharField(blank=True, max_length=120)),
                ('processor', models.CharField(blank=True, max_length=200)),
                ('motherboard_manufacturer', models.CharField(blank=True, max_length=150)),
                ('motherboard_model', models.CharField(blank=True, max_length=150)),
                ('motherboard_serial', models.CharField(blank=True, max_length=120)),
                ('bios_serial', models.CharField(blank=True, max_length=120)),
                ('ram_total', models.CharField(blank=True, max_length=40)),
                ('ram_devices', models.JSONField(blank=True, default=list)),
                ('storage_devices', models.JSONField(blank=True, default=list)),
                ('monitor_name', models.CharField(blank=True, max_length=150)),
                ('monitor_serial', models.CharField(blank=True, max_length=120)),
                ('monitor_manufacturer', models.CharField(blank=True, max_length=150)),
                ('mouse_name', models.CharField(blank=True, max_length=150)),
                ('mouse_serial', models.CharField(blank=True, max_length=120)),
                ('keyboard_name', models.CharField(blank=True, max_length=150)),
                ('keyboard_serial', models.CharField(blank=True, max_length=120)),
                ('ups_name', models.CharField(blank=True, max_length=150)),
                ('ups_serial', models.CharField(blank=True, max_length=120)),
                ('ups_capacity', models.CharField(blank=True, max_length=60)),
                ('asset_tag', models.CharField(blank=True, max_length=80)),
                ('vendor', models.CharField(blank=True, max_length=150)),
                ('purchase_date', models.CharField(blank=True, max_length=60)),
                ('handover_date', models.CharField(blank=True, max_length=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='core.device')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.branch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='core.employee'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_device', 'New computer registered'), ('new_employee', 'New employee added'), ('hardware_change', 'Hardware replacement detected'), ('device_offline', 'Device removed from the network'), ('sync_failed', 'Synchronization failed'), ('duplicate_asset', 'Duplicate asset detected'), ('missing_info', 'Missing hardware information')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('message', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150)),
                ('model', models.CharField(blank=True, max_length=150)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('date_purchased', models.CharField(blank=True, max_length=60)),
                ('warranty_expiry', models.CharField(blank=True, max_length=60)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printers', to='core.branch')),
            ],
            options={
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('detail', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='core.device')),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
    ]
