# Generated by Django 6.0.7 on 2026-08-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='cpu_architecture',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='cpu_clock_speed',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='asset',
            name='cpu_cores',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='cpu_manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='cpu_threads',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='keyboard_brand',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='asset',
            name='monitor_manufacture_date',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='asset',
            name='monitor_resolution',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='monitor_screen_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='mouse_brand',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='asset',
            name='serial_verification',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='asset',
            name='system_brand',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
