# Generated by Django 6.0.7 on 2026-08-03 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asset_cpu_architecture_asset_cpu_clock_speed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='e.g. 1.4.2', max_length=30)),
                ('channel', models.CharField(choices=[('stable', 'Stable'), ('beta', 'Beta')], default='stable', max_length=10)),
                ('changelog', models.TextField(blank=True, help_text='Shown to users before they update.')),
                ('download_url', models.URLField(help_text='Direct download link for this build (e.g. a GitHub Release asset URL).', max_length=500)),
                ('sha256', models.CharField(blank=True, help_text="Optional SHA-256 of the EXE, so the client can verify the download wasn't corrupted.", max_length=64)),
                ('is_mandatory', models.BooleanField(default=False, help_text='If checked, devices on an older version must update before continuing to sync.')),
                ('is_latest', models.BooleanField(default=False, help_text='The version devices on this channel are told to update to. Only one per channel.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to pull a broken release from circulation without deleting its history.')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at'],
                'unique_together': {('version', 'channel')},
            },
        ),
    ]
