# Generated by Django 6.0.7 on 2026-08-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_apprelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='app_version',
            field=models.CharField(blank=True, help_text='Version of the client EXE last reported by this device (via sync or heartbeat).', max_length=20),
        ),
    ]
