# Generated by Django 6.0.7 on 2026-08-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_device_app_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('seen', 'Seen by employee'), ('acknowledged', 'Acknowledged by employee'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
    ]
