# Generated by Django 6.0.7 on 2026-08-15 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_command_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('active', 'Active'), ('maintenance', 'Under Maintenance'), ('replaced', 'Replaced'), ('returned', 'Returned'), ('transferred', 'Transferred'), ('retired', 'Retired'), ('lost', 'Lost'), ('decommissioned', 'Decommissioned')], default='active', help_text="Lifecycle status of this physical device, independent of whether it's currently online.", max_length=20),
        ),
        migrations.CreateModel(
            name='DeviceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('temporary', 'Temporary')], default='primary', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Exactly one active assignment per device at a time.')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Why this transfer/assignment happened, if relevant.')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_assignments', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.device')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_assignments', to='core.employee')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
