# Generated by Django 6.1 on 2026-09-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_device_status_deviceassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_device', 'New computer registered'), ('new_employee', 'New employee added'), ('hardware_change', 'Hardware replacement detected'), ('device_offline', 'Device removed from the network'), ('sync_failed', 'Synchronization failed'), ('duplicate_asset', 'Duplicate asset detected'), ('missing_info', 'Missing hardware information'), ('multiple_devices', 'Employee has multiple active devices')], max_length=20),
        ),
    ]
